---
title: "Pink Salmon Forecasting Update"
format: docx
editor: visual
---

Over the last three years the UW-ASP group developed new methods based
on modern tools such as machine learning to increase our capability of
incorporating environmental data as well as the effects of other salmon
species and stocks that interact with Bristol Bay sockeye to improve
preseason forecast accuracy.  We are now applying these methods to
explore their potential for improving preseason forecasts of pink salmon
in Alaska, specifically in Southeast Alaska (SEA), Prince William Sound
(PWS), and Kodiak (KOD) regions.

We gathered data on historic pink salmon returns in even and odd years
across eleven sub-regions within the three main regions of SEA, PWS, and
KOD. We augmented these pink salmon data with sea surface temperature in
targeted regions of the Gulf of Alaska, Pacific Decadal Oscillation
data, hatchery releases from the NPAFC, the SECM survey juvenile index,
and the Icy Strait sea surface temperature index from thee SECM survey.

We then trained a range of models on these data and assessed how well
they performed relative to a benchmark "persistence" model, where the
forecast for returns for a given stock this year are equal to the
observed returns of that stock the prior year.

We found promising but variable results; our models reduced pre-season
forecast error by as little as 0% (PWS) and as much as 25% (KOD). We are
currently working with local forecasting teams to assess our results and
determine the best way to interpret and communicate our results, and
where appropriate incorporate them into pre-season pink salmon
forecasts.
